app/models.py
from app import db, login
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from flask import current_app


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    expert = db.Column(db.Boolean, default=False)
    admin = db.Column(db.Boolean, default=False)
    
    questions = db.relationship(
        'Question',
        foreign_keys='Question.asked_by_id',
        backref='asker',
        lazy=True)

    answered_requested = db.relationship(
        'Question',
        foreign_keys='Question.expert_id',
        backref='expert',
        lazy=True)

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class Question(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    question = db.Column(db.Text)
    answer = db.Column(db.Text)
    asked_by_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    expert_id = db.Column(db.Integer, db.ForeignKey('user.id'))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, \
    SelectField
from wtforms.validators import DataRequired
from wtforms_sqlalchemy.fields import QuerySelectField
from app.models import User



def expert_users():
    return User.query.filter_by(expert=True)


def get_pk(obj):
    return str(obj)


class AskQuestionForm(FlaskForm):
    question = TextAreaField('Question')
    experts = QuerySelectField(
        query_factory=expert_users,
        allow_blank=True,
        get_pk=get_pk,
        get_label='username')
    submit = SubmitField('Ask')


class AnswerQuestionForm(FlaskForm):
    question = TextAreaField('Question')
    answer = TextAreaField('Answer')
    submit = SubmitField('Answer')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app



from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from app import db
from flask import render_template, url_for, flash, redirect, request
from flask_login import current_user, login_user, logout_user, login_required
from app.models import User, Question
from werkzeug.urls import url_parse
from app.main import bp
from app.main.forms import AskQuestionForm, AnswerQuestionForm


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    questions = Question.query.filter(Question.answer != None).all()
    return render_template(
        'index.html', questions=questions)


@bp.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    form = AskQuestionForm()
    if form.validate_on_submit():
        question_asked = form.question.data
        asker_id = current_user.id
        expert = form.experts.data.id
        question = Question(
            question=question_asked,
            asked_by_id=asker_id,
            expert_id=expert
        )
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('main.index'))
    return render_template('ask.html', form=form)


@bp.route('/unanswered')
@login_required
def unanswered():
    if not current_user.expert:
        return redirect(url_for('main.index'))
    unanswered_questions = Question.query\
        .filter_by(expert_id=current_user.id)\
        .filter(Question.answer == None)\
        .all()
    return render_template(
        'unanswered.html', unanswered_questions=unanswered_questions)


@bp.route('/answer/<int:question_id>', methods=['GET', 'POST'])
@login_required
def answer(question_id):
    if not current_user.expert:
        return redirect(url_for('main.index'))
    question = Question.query.get_or_404(question_id)
    form = AnswerQuestionForm()
    if form.validate_on_submit():
        question.answer = form.answer.data
        db.session.commit()
        return redirect(url_for('main.unanswered'))
    return render_template(
        'answer.html', form=form, question=question)


@bp.route('/question/<int:question_id>')
@login_required
def question(question_id):
    question = Question.query.get_or_404(question_id)
    return render_template('question.html', question=question)


@bp.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    if not current_user.admin:
        return redirect(url_for('main.index'))
    users = User.query.all()
    return render_template('users.html', users=users)


@bp.route('/promote/<int:user_id>', methods=['GET', 'POST'])
@login_required
def promote(user_id):
    if not current_user.admin:
        return redirect(url_for('main.index'))
    user = User.query.get_or_404(user_id)
    if user.expert:
        user.expert = False
    else:
        user.expert = True
    db.session.commit()
    return redirect(url_for('main.users'))
    return render_template('users.html', user=user)

app/templates/answer.html
{% extends "base.html" %}
{% block title %}Answer A Question{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="page-header pt-4">
            <h1>{{ question.question }}</h1>
        </div>
        <hr>
        <p>
            {{ form.question.label }}:
            {{ form.question(cols="60", rows="3", class="form-control")}}
        </p>
        <p>{{ form.submit(class="btn btn-primary") }}</p>
    </form>
{% endblock %}

app/templates/ask.html
{% extends "base.html" %}
{% block title %}Ask A Question{% endblock %}

{% block content %}

<div class="d-flex justify-content-center">
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="page-header pt-4">
            <h1>Ask A Question</h1>
        </div>
        <hr>
        <p>
            {{ form.question.label }}: 
            {{ form.question(cols="60", rows="3", class="form-control")}}
        </p>
        <p>
            {{ form.experts.label }}:
            {{ form.experts(class="form-control") }}

        </p>
        <p>{{ form.submit(class="btn btn-primary") }}</p>
    </form>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}Micro Q&A{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Flask Q&A</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('main.index') }}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if current_user.is_authenticated and current_user.expert %}
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('main.unanswered') }}">Unanswered Questions</a>
          </li>
          {% endif %}
          {% if current_user.is_authenticated %}
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('main.ask') }}">Ask</a>
          </li>
          {% endif %}
          {% if current_user.is_authenticated and current_user.admin %}
          <li class="nav-item ">
            <a class="nav-link" href="{{ url_for('main.users') }}">Users</a>
          </li>
          {% endif %}
          {% if current_user.is_anonymous %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-success d-flex justify-content-center" role="alert">
      {% for message in messages %}
        {{ message }}
      {% endfor %}
    </div>
    {% endif %}
    {% endwith %}
    <div class="container">
      {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block title %}Questions & Answers{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-lg-8">
        <div class="page-header pt-4">
            <h1>Hi, {{ current_user.username|capitalize }}</h1>
            {% if not current_user.expert %}
            <h3>What do you want to ask our experts?</h3>
            {% else %}
            <h3>Are there any questions that need answers?</h3>
            {% endif %}
        </div>
        <hr>
        <div class="list-group">
            {% for question in questions %}
            <a href="{{ url_for('main.question', question_id=question.id) }}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ question.question }}</h5>
                </div>
                <p class="mb-1">Asked by: {{ question.asker.username|capitalize }}</p>
                <p class="mb-1">Answered by: {{ question.expert.username|capitalize }}</p>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/question.html
{% extends 'base.html' %}
{% block title %}Question{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-lg-8">
        <h1>{{ question.question }}</h1>
        <p>{{ question.answer }}</p>
        <div class="list-group">
            <a href="#" class="list-group-item list-group-item-action list-group-item-info">Asked By: {{ question.asker.username }}</a>
        <a href="#" class="list-group-item list-group-item-action list-group-item-primary">Answered By: {{ question.expert.username }}</a>
        </div>
    </div>
</div>
{% endblock %}

app/templates/unanswered.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center">
    <div class="col-lg-8">
        <div class="page-header pt-4">
            <h1>Question For You</h1>
        </div>
        <hr>
        <div class="list-group">
            {% for question  in unanswered_questions %}
            <a href="{{ url_for('main.answer', question_id=question.id) }}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ question.question }}</h5>
                </div>
                <p class="mb-1">Asked by: {{ question.asker.username }}</p>
            </a>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/users.html
{% extends 'base.html' %}
{% block title %}{% endblock %}

{% block content %}
<div class="row d-flex justify-content-center">
    <div class="col-lg-8">
        <div class="page-header pt-4">
            <h1>Users</h1>
        </div>
        <hr>
        <div class="list-group">
            {% for user in users %}
            <a href="{{ url_for('main.promote', user_id=user.id) }}" 
                class="list-group-item {% if user.expert %}active{% endif %}">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ user.username|capitalize }}</h5>
                    {% if user.expert %}
                    <h5>This user is an expert on the site</h5>
                    {% endif %}
                </div>
            </a> 
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}